# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language: python
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.3
  hooks:
    - id: ruff
      args: [dtbase, infrastructure, --fix]
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.6.0
  hooks:
  - id: prettier
    files: ^dtbase/webapp
    args: [--ignore-path=dtbase/webapp/.prettierignore]
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
  - id: eslint
    exclude: ^dtbase/webapp/node_modules
    files: \.tsx?$
    types: [file]
