services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.db
    image: dtbase_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dt_dev
    volumes:
      - app_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    image: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DT_SQL_USER=postgres
      - DT_SQL_PASS=password
      - DT_SQL_HOST=db
      - DT_SQL_PORT=5432
      - DT_SQL_DBNAME=dt_dev
      - DT_DEFAULT_USER_PASS=password
      - DT_JWT_SECRET_KEY=<REPLACE_ME>
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    image: frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      #- DT_DEFAULT_USER_PASS=password
      - DT_FRONT_SECRET_KEY=banana
      - DT_BACKEND_URL=http://backend:5000
volumes:
  app_data:
