FROM ubuntu:22.04

# Upgrade various packages and install python
RUN apt update
RUN apt dist-upgrade -y
RUN apt install -y build-essential
RUN apt install -y python3-pip
RUN apt install -y python3.10
RUN rm -f /usr/bin/python3 && ln -s /usr/bin/python3.11 /usr/bin/python3
RUN rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
RUN python3 -m pip install --upgrade pip

# Install nodejs/npm (requires first installing CURL)
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt install -y nodejs

# Copy dtbase over and install it
RUN mkdir DTBase
WORKDIR DTBase
ADD dtbase dtbase
ADD pyproject.toml pyproject.toml
RUN python3 -m pip install .

# launch the webapp
WORKDIR /DTBase/dtbase/webapp
EXPOSE 8000
CMD ["./run.sh"]
