FROM mcr.microsoft.com/azure-functions/python:4-python3.10-appservice

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY dtbase /dtbase
COPY pyproject.toml /
RUN pip install .

COPY dtbase/functions/. /home/site/wwwroot
