MOCKED_CONST_OPENWEATHERMAP_HISTORICAL_URL_RESPONSE = {
    "lat": 31,
    "lon": 0,
    "timezone": "Africa/Algiers",
    "timezone_offset": 3600,
    "current": {
        "dt": 1704464778,
        "sunrise": 1704437924,
        "sunset": 1704474665,
        "temp": 20.39,
        "feels_like": 19.01,
        "pressure": 1011,
        "humidity": 20,
        "dew_point": -2.92,
        "uvi": 2.11,
        "clouds": 0,
        "visibility": 10000,
        "wind_speed": 8.82,
        "wind_deg": 255,
        "wind_gust": 10.31,
        "weather": [
            {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
        ],
    },
    "hourly": [
        {
            "dt": 1704412800,
            "temp": 11.59,
            "feels_like": 9.72,
            "pressure": 1017,
            "humidity": 35,
            "dew_point": -2.95,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 3.94,
            "wind_deg": 235,
            "wind_gust": 3.91,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
        },
        {
            "dt": 1704416400,
            "temp": 11.58,
            "feels_like": 9.71,
            "pressure": 1017,
            "humidity": 35,
            "dew_point": -2.96,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.2,
            "wind_deg": 240,
            "wind_gust": 4.21,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
        },
        {
            "dt": 1704420000,
            "temp": 11.35,
            "feels_like": 9.45,
            "pressure": 1017,
            "humidity": 35,
            "dew_point": -3.14,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.23,
            "wind_deg": 239,
            "wind_gust": 4.31,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
        },
        {
            "dt": 1704423600,
            "temp": 11.17,
            "feels_like": 9.28,
            "pressure": 1016,
            "humidity": 36,
            "dew_point": -2.95,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.43,
            "wind_deg": 236,
            "wind_gust": 5.3,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
        },
        {
            "dt": 1704427200,
            "temp": 10.77,
            "feels_like": 8.87,
            "pressure": 1016,
            "humidity": 37,
            "dew_point": -2.94,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.47,
            "wind_deg": 245,
            "wind_gust": 5.4,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
        },
        {
            "dt": 1704430800,
            "temp": 11.03,
            "feels_like": 9.13,
            "pressure": 1016,
            "humidity": 36,
            "dew_point": -3.06,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.35,
            "wind_deg": 244,
            "wind_gust": 5.5,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
        },
        {
            "dt": 1704434400,
            "temp": 10.36,
            "feels_like": 8.44,
            "pressure": 1016,
            "humidity": 38,
            "dew_point": -2.95,
            "uvi": 0,
            "clouds": 5,
            "visibility": 10000,
            "wind_speed": 4.35,
            "wind_deg": 250,
            "wind_gust": 5.2,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
        },
        {
            "dt": 1704438000,
            "temp": 9.74,
            "feels_like": 7.55,
            "pressure": 1016,
            "humidity": 39,
            "dew_point": -3.13,
            "uvi": 0,
            "clouds": 5,
            "visibility": 10000,
            "wind_speed": 4.3,
            "wind_deg": 243,
            "wind_gust": 4.32,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704441600,
            "temp": 10.55,
            "feels_like": 8.63,
            "pressure": 1016,
            "humidity": 37,
            "dew_point": -3.11,
            "uvi": 0.35,
            "clouds": 3,
            "visibility": 10000,
            "wind_speed": 4.53,
            "wind_deg": 249,
            "wind_gust": 7.3,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704445200,
            "temp": 13.16,
            "feels_like": 11.34,
            "pressure": 1016,
            "humidity": 31,
            "dew_point": -3.17,
            "uvi": 1.09,
            "clouds": 2,
            "visibility": 10000,
            "wind_speed": 5.27,
            "wind_deg": 255,
            "wind_gust": 9,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704448800,
            "temp": 15.99,
            "feels_like": 14.32,
            "pressure": 1016,
            "humidity": 26,
            "dew_point": -3.09,
            "uvi": 2.1,
            "clouds": 1,
            "visibility": 10000,
            "wind_speed": 6.31,
            "wind_deg": 253,
            "wind_gust": 9.51,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704452400,
            "temp": 18.09,
            "feels_like": 16.56,
            "pressure": 1014,
            "humidity": 23,
            "dew_point": -2.96,
            "uvi": 3,
            "clouds": 1,
            "visibility": 10000,
            "wind_speed": 7.07,
            "wind_deg": 253,
            "wind_gust": 9.5,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704456000,
            "temp": 19.55,
            "feels_like": 18.11,
            "pressure": 1013,
            "humidity": 21,
            "dew_point": -2.96,
            "uvi": 3.38,
            "clouds": 1,
            "visibility": 10000,
            "wind_speed": 7.65,
            "wind_deg": 250,
            "wind_gust": 9.4,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704459600,
            "temp": 20.3,
            "feels_like": 18.91,
            "pressure": 1011,
            "humidity": 20,
            "dew_point": -2.99,
            "uvi": 2.99,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 8.12,
            "wind_deg": 253,
            "wind_gust": 9.72,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704463200,
            "temp": 20.39,
            "feels_like": 19.01,
            "pressure": 1011,
            "humidity": 20,
            "dew_point": -2.92,
            "uvi": 2.11,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 8.82,
            "wind_deg": 255,
            "wind_gust": 10.31,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704466800,
            "temp": 20.2,
            "feels_like": 18.8,
            "pressure": 1010,
            "humidity": 20,
            "dew_point": -3.06,
            "uvi": 1.07,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 8.66,
            "wind_deg": 263,
            "wind_gust": 10.41,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
        {
            "dt": 1704470400,
            "temp": 19.52,
            "feels_like": 18.08,
            "pressure": 1011,
            "humidity": 21,
            "dew_point": -2.98,
            "uvi": 0.33,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 7.27,
            "wind_deg": 270,
            "wind_gust": 9.71,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
        },
    ],
}

EXPECTED_OPENWEATHERMAP_HISTORICAL_GET_DATA_RESPONSE = [
    (
        "/sensor/insert-sensor-type",
        {
            "name": "Weather",
            "description": "Weather sensors and sensor-like data sources, such as weather forecast sources.",
            "measures": [
                {
                    "name": "temperature",
                    "units": "degrees Celsius",
                    "datatype": "float",
                },
                {
                    "name": "relative humidity",
                    "units": "percent",
                    "datatype": "integer",
                },
                {"name": "air pressure", "units": "millibar", "datatype": "integer"},
                {"name": "wind speed", "units": "m/s", "datatype": "float"},
                {"name": "wind direction", "units": "degrees", "datatype": "integer"},
                {"name": "rain", "units": "mms", "datatype": "float"},
                {"name": "icon", "units": "", "datatype": "string"},
            ],
        },
    ),
    (
        "/sensor/insert-sensor",
        {
            "unique_identifier": "OpenWeatherMapHistory",
            "type_name": "Weather",
            "name": "OpenWeatherMap Historical Data",
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "temperature",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": (20.2, 19.52),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "air pressure",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": (1010, 1011),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "relative humidity",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": (20, 21),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "wind speed",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": (8.66, 7.27),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "wind direction",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": (263, 270),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "icon",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": ("01d", "01d"),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "rain",
            "unique_identifier": "OpenWeatherMapHistory",
            "readings": (0.0, 0.0),
            "timestamps": ("2024-01-05T15:00:00", "2024-01-05T16:00:00"),
        },
    ),
]

MOCKED_CONST_OPENWEATHERMAP_FORECAST_URL_RESPONSE = {
    "lat": 31,
    "lon": 0,
    "timezone": "Africa/Algiers",
    "timezone_offset": 3600,
    "current": {
        "dt": 1704472291,
        "sunrise": 1704437924,
        "sunset": 1704474665,
        "temp": 16.69,
        "feels_like": 15.07,
        "pressure": 1011,
        "humidity": 25,
        "dew_point": -3.02,
        "uvi": 0,
        "clouds": 0,
        "visibility": 10000,
        "wind_speed": 5.25,
        "wind_deg": 269,
        "wind_gust": 7.61,
        "weather": [
            {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
        ],
    },
    "hourly": [
        {
            "dt": 1704470400,
            "temp": 17.23,
            "feels_like": 15.64,
            "pressure": 1011,
            "humidity": 24,
            "dew_point": -3.1,
            "uvi": 0.33,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 7.26,
            "wind_deg": 271,
            "wind_gust": 9.69,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704474000,
            "temp": 16.69,
            "feels_like": 15.07,
            "pressure": 1011,
            "humidity": 25,
            "dew_point": -3.02,
            "uvi": 0,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 5.25,
            "wind_deg": 269,
            "wind_gust": 7.61,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704477600,
            "temp": 16.41,
            "feels_like": 14.79,
            "pressure": 1011,
            "humidity": 26,
            "dew_point": -2.77,
            "uvi": 0,
            "clouds": 0,
            "visibility": 10000,
            "wind_speed": 4.82,
            "wind_deg": 264,
            "wind_gust": 4.9,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704481200,
            "temp": 15.9,
            "feels_like": 14.25,
            "pressure": 1012,
            "humidity": 27,
            "dew_point": -2.71,
            "uvi": 0,
            "clouds": 2,
            "visibility": 10000,
            "wind_speed": 4.47,
            "wind_deg": 284,
            "wind_gust": 4.41,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704484800,
            "temp": 15.34,
            "feels_like": 13.71,
            "pressure": 1013,
            "humidity": 30,
            "dew_point": -1.88,
            "uvi": 0,
            "clouds": 5,
            "visibility": 10000,
            "wind_speed": 8.31,
            "wind_deg": 339,
            "wind_gust": 13.65,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704488400,
            "temp": 14.62,
            "feels_like": 12.97,
            "pressure": 1014,
            "humidity": 32,
            "dew_point": -1.66,
            "uvi": 0,
            "clouds": 6,
            "visibility": 10000,
            "wind_speed": 9.32,
            "wind_deg": 324,
            "wind_gust": 14.07,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704492000,
            "temp": 11.54,
            "feels_like": 9.95,
            "pressure": 1017,
            "humidity": 46,
            "dew_point": 0.36,
            "uvi": 0,
            "clouds": 10,
            "visibility": 10000,
            "wind_speed": 5.19,
            "wind_deg": 344,
            "wind_gust": 7.15,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704495600,
            "temp": 10.57,
            "feels_like": 9.14,
            "pressure": 1017,
            "humidity": 56,
            "dew_point": 2.18,
            "uvi": 0,
            "clouds": 8,
            "visibility": 10000,
            "wind_speed": 5.11,
            "wind_deg": 341,
            "wind_gust": 7.25,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704499200,
            "temp": 10.23,
            "feels_like": 8.41,
            "pressure": 1017,
            "humidity": 42,
            "dew_point": -1.94,
            "uvi": 0,
            "clouds": 7,
            "visibility": 10000,
            "wind_speed": 7.1,
            "wind_deg": 349,
            "wind_gust": 12.79,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "pop": 0,
        },
        {
            "dt": 1704502800,
            "temp": 9.75,
            "feels_like": 6.33,
            "pressure": 1018,
            "humidity": 43,
            "dew_point": -2.2,
            "uvi": 0,
            "clouds": 76,
            "visibility": 10000,
            "wind_speed": 8.06,
            "wind_deg": 350,
            "wind_gust": 13.95,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704506400,
            "temp": 9.43,
            "feels_like": 6.01,
            "pressure": 1018,
            "humidity": 45,
            "dew_point": -1.78,
            "uvi": 0,
            "clouds": 88,
            "visibility": 10000,
            "wind_speed": 7.71,
            "wind_deg": 349,
            "wind_gust": 13.21,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704510000,
            "temp": 9.19,
            "feels_like": 5.94,
            "pressure": 1018,
            "humidity": 44,
            "dew_point": -2.49,
            "uvi": 0,
            "clouds": 92,
            "visibility": 10000,
            "wind_speed": 6.87,
            "wind_deg": 340,
            "wind_gust": 12.72,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704513600,
            "temp": 8.87,
            "feels_like": 5.44,
            "pressure": 1018,
            "humidity": 41,
            "dew_point": -3.5,
            "uvi": 0,
            "clouds": 94,
            "visibility": 10000,
            "wind_speed": 7.16,
            "wind_deg": 340,
            "wind_gust": 12.56,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704517200,
            "temp": 7.27,
            "feels_like": 4.01,
            "pressure": 1019,
            "humidity": 48,
            "dew_point": -3.06,
            "uvi": 0,
            "clouds": 84,
            "visibility": 10000,
            "wind_speed": 5.4,
            "wind_deg": 356,
            "wind_gust": 9.04,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704520800,
            "temp": 6.61,
            "feels_like": 3.14,
            "pressure": 1020,
            "humidity": 53,
            "dew_point": -2.14,
            "uvi": 0,
            "clouds": 79,
            "visibility": 10000,
            "wind_speed": 5.5,
            "wind_deg": 13,
            "wind_gust": 9.73,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704524400,
            "temp": 5.86,
            "feels_like": 2.99,
            "pressure": 1021,
            "humidity": 58,
            "dew_point": -1.72,
            "uvi": 0,
            "clouds": 40,
            "visibility": 10000,
            "wind_speed": 3.87,
            "wind_deg": 18,
            "wind_gust": 4.24,
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704528000,
            "temp": 6.94,
            "feels_like": 4.8,
            "pressure": 1022,
            "humidity": 56,
            "dew_point": -1.32,
            "uvi": 0.34,
            "clouds": 71,
            "visibility": 10000,
            "wind_speed": 3.05,
            "wind_deg": 30,
            "wind_gust": 5.75,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704531600,
            "temp": 8.7,
            "feels_like": 6.68,
            "pressure": 1022,
            "humidity": 50,
            "dew_point": -1.23,
            "uvi": 1.12,
            "clouds": 81,
            "visibility": 10000,
            "wind_speed": 3.46,
            "wind_deg": 33,
            "wind_gust": 6.51,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704535200,
            "temp": 11.11,
            "feels_like": 9.24,
            "pressure": 1023,
            "humidity": 37,
            "dew_point": -2.85,
            "uvi": 2.11,
            "clouds": 65,
            "visibility": 10000,
            "wind_speed": 3.92,
            "wind_deg": 360,
            "wind_gust": 7.79,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704538800,
            "temp": 13.76,
            "feels_like": 11.9,
            "pressure": 1021,
            "humidity": 27,
            "dew_point": -4.95,
            "uvi": 3.11,
            "clouds": 54,
            "visibility": 10000,
            "wind_speed": 5.77,
            "wind_deg": 349,
            "wind_gust": 7.75,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704542400,
            "temp": 14.96,
            "feels_like": 13.14,
            "pressure": 1020,
            "humidity": 24,
            "dew_point": -5.35,
            "uvi": 3.29,
            "clouds": 59,
            "visibility": 10000,
            "wind_speed": 7.02,
            "wind_deg": 346,
            "wind_gust": 7.96,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704546000,
            "temp": 15.75,
            "feels_like": 13.98,
            "pressure": 1019,
            "humidity": 23,
            "dew_point": -5.55,
            "uvi": 2.9,
            "clouds": 73,
            "visibility": 10000,
            "wind_speed": 6.17,
            "wind_deg": 332,
            "wind_gust": 6.97,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704549600,
            "temp": 16.15,
            "feels_like": 14.37,
            "pressure": 1019,
            "humidity": 21,
            "dew_point": -5.99,
            "uvi": 1.94,
            "clouds": 75,
            "visibility": 10000,
            "wind_speed": 5.1,
            "wind_deg": 321,
            "wind_gust": 6.16,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704553200,
            "temp": 16.27,
            "feels_like": 14.47,
            "pressure": 1018,
            "humidity": 20,
            "dew_point": -6.63,
            "uvi": 0.8,
            "clouds": 83,
            "visibility": 10000,
            "wind_speed": 3.46,
            "wind_deg": 300,
            "wind_gust": 5.37,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704556800,
            "temp": 16.06,
            "feels_like": 14.24,
            "pressure": 1018,
            "humidity": 20,
            "dew_point": -6.88,
            "uvi": 0.3,
            "clouds": 87,
            "visibility": 10000,
            "wind_speed": 3.74,
            "wind_deg": 276,
            "wind_gust": 4.64,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704560400,
            "temp": 14.43,
            "feels_like": 12.53,
            "pressure": 1019,
            "humidity": 23,
            "dew_point": -6.36,
            "uvi": 0,
            "clouds": 90,
            "visibility": 10000,
            "wind_speed": 4.3,
            "wind_deg": 272,
            "wind_gust": 5.23,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704564000,
            "temp": 12.84,
            "feels_like": 10.96,
            "pressure": 1019,
            "humidity": 30,
            "dew_point": -4.45,
            "uvi": 0,
            "clouds": 91,
            "visibility": 10000,
            "wind_speed": 4.55,
            "wind_deg": 272,
            "wind_gust": 6.23,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704567600,
            "temp": 11.95,
            "feels_like": 10.06,
            "pressure": 1020,
            "humidity": 33,
            "dew_point": -3.86,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.59,
            "wind_deg": 259,
            "wind_gust": 6.05,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704571200,
            "temp": 11.48,
            "feels_like": 9.55,
            "pressure": 1020,
            "humidity": 33,
            "dew_point": -4.01,
            "uvi": 0,
            "clouds": 100,
            "visibility": 10000,
            "wind_speed": 4.28,
            "wind_deg": 250,
            "wind_gust": 5.05,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704574800,
            "temp": 10.29,
            "feels_like": 8.31,
            "pressure": 1021,
            "humidity": 36,
            "dew_point": -4.21,
            "uvi": 0,
            "clouds": 98,
            "visibility": 10000,
            "wind_speed": 4.08,
            "wind_deg": 245,
            "wind_gust": 3.98,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704578400,
            "temp": 9.28,
            "feels_like": 7.08,
            "pressure": 1021,
            "humidity": 38,
            "dew_point": -4.34,
            "uvi": 0,
            "clouds": 86,
            "visibility": 10000,
            "wind_speed": 4.09,
            "wind_deg": 244,
            "wind_gust": 3.99,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704582000,
            "temp": 8.81,
            "feels_like": 6.45,
            "pressure": 1022,
            "humidity": 39,
            "dew_point": -4.47,
            "uvi": 0,
            "clouds": 71,
            "visibility": 10000,
            "wind_speed": 4.18,
            "wind_deg": 252,
            "wind_gust": 4.09,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704585600,
            "temp": 8.35,
            "feels_like": 5.96,
            "pressure": 1022,
            "humidity": 39,
            "dew_point": -4.72,
            "uvi": 0,
            "clouds": 60,
            "visibility": 10000,
            "wind_speed": 4.04,
            "wind_deg": 250,
            "wind_gust": 4.05,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704589200,
            "temp": 7.96,
            "feels_like": 5.74,
            "pressure": 1022,
            "humidity": 40,
            "dew_point": -4.93,
            "uvi": 0,
            "clouds": 80,
            "visibility": 10000,
            "wind_speed": 3.53,
            "wind_deg": 258,
            "wind_gust": 3.52,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704592800,
            "temp": 7.68,
            "feels_like": 5.29,
            "pressure": 1022,
            "humidity": 40,
            "dew_point": -4.95,
            "uvi": 0,
            "clouds": 40,
            "visibility": 10000,
            "wind_speed": 3.73,
            "wind_deg": 254,
            "wind_gust": 3.73,
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704596400,
            "temp": 7.32,
            "feels_like": 5.02,
            "pressure": 1022,
            "humidity": 41,
            "dew_point": -4.92,
            "uvi": 0,
            "clouds": 27,
            "visibility": 10000,
            "wind_speed": 3.43,
            "wind_deg": 262,
            "wind_gust": 3.4,
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704600000,
            "temp": 7.07,
            "feels_like": 4.85,
            "pressure": 1021,
            "humidity": 42,
            "dew_point": -4.88,
            "uvi": 0,
            "clouds": 21,
            "visibility": 10000,
            "wind_speed": 3.22,
            "wind_deg": 276,
            "wind_gust": 3.2,
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704603600,
            "temp": 6.78,
            "feels_like": 4.62,
            "pressure": 1021,
            "humidity": 43,
            "dew_point": -4.98,
            "uvi": 0,
            "clouds": 18,
            "visibility": 10000,
            "wind_speed": 3.03,
            "wind_deg": 272,
            "wind_gust": 3.02,
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704607200,
            "temp": 6.49,
            "feels_like": 4.39,
            "pressure": 1022,
            "humidity": 43,
            "dew_point": -5.06,
            "uvi": 0,
            "clouds": 21,
            "visibility": 10000,
            "wind_speed": 2.86,
            "wind_deg": 279,
            "wind_gust": 2.91,
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704610800,
            "temp": 6.48,
            "feels_like": 4.36,
            "pressure": 1022,
            "humidity": 43,
            "dew_point": -5.08,
            "uvi": 0,
            "clouds": 72,
            "visibility": 10000,
            "wind_speed": 2.89,
            "wind_deg": 283,
            "wind_gust": 2.91,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704614400,
            "temp": 7.99,
            "feels_like": 6.56,
            "pressure": 1022,
            "humidity": 39,
            "dew_point": -5.07,
            "uvi": 0.36,
            "clouds": 84,
            "visibility": 10000,
            "wind_speed": 2.34,
            "wind_deg": 294,
            "wind_gust": 2.42,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704618000,
            "temp": 10.36,
            "feels_like": 8.31,
            "pressure": 1022,
            "humidity": 33,
            "dew_point": -5.07,
            "uvi": 1.1,
            "clouds": 89,
            "visibility": 10000,
            "wind_speed": 2.58,
            "wind_deg": 310,
            "wind_gust": 3.62,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704621600,
            "temp": 12.39,
            "feels_like": 10.44,
            "pressure": 1022,
            "humidity": 29,
            "dew_point": -5.03,
            "uvi": 2.14,
            "clouds": 92,
            "visibility": 10000,
            "wind_speed": 2.59,
            "wind_deg": 312,
            "wind_gust": 3.6,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704625200,
            "temp": 14.1,
            "feels_like": 12.24,
            "pressure": 1021,
            "humidity": 26,
            "dew_point": -5,
            "uvi": 3.06,
            "clouds": 89,
            "visibility": 10000,
            "wind_speed": 2.56,
            "wind_deg": 297,
            "wind_gust": 3.49,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704628800,
            "temp": 15.54,
            "feels_like": 13.78,
            "pressure": 1020,
            "humidity": 24,
            "dew_point": -5.01,
            "uvi": 3.43,
            "clouds": 76,
            "visibility": 10000,
            "wind_speed": 3.05,
            "wind_deg": 278,
            "wind_gust": 4.09,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704632400,
            "temp": 16.63,
            "feels_like": 14.92,
            "pressure": 1019,
            "humidity": 22,
            "dew_point": -5.07,
            "uvi": 3.04,
            "clouds": 72,
            "visibility": 10000,
            "wind_speed": 3.86,
            "wind_deg": 269,
            "wind_gust": 4.82,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704636000,
            "temp": 17.3,
            "feels_like": 15.63,
            "pressure": 1018,
            "humidity": 21,
            "dew_point": -5.13,
            "uvi": 2.11,
            "clouds": 46,
            "visibility": 10000,
            "wind_speed": 4.24,
            "wind_deg": 262,
            "wind_gust": 5.11,
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "pop": 0,
        },
        {
            "dt": 1704639600,
            "temp": 17.49,
            "feels_like": 15.84,
            "pressure": 1018,
            "humidity": 21,
            "dew_point": -5.18,
            "uvi": 1.1,
            "clouds": 46,
            "visibility": 10000,
            "wind_speed": 4.67,
            "wind_deg": 262,
            "wind_gust": 5.53,
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "pop": 0,
        },
    ],
    "daily": [
        {
            "dt": 1704456000,
            "sunrise": 1704437924,
            "sunset": 1704474665,
            "moonrise": 1704416160,
            "moonset": 1704457260,
            "moon_phase": 0.79,
            "summary": "The day will start with partly cloudy through the late morning hours, transitioning to clearing",
            "temp": {
                "day": 19.39,
                "min": 9.8,
                "max": 19.46,
                "night": 11.54,
                "eve": 16.41,
                "morn": 10.53,
            },
            "feels_like": {"day": 17.93, "night": 9.95, "eve": 14.79, "morn": 8.6},
            "pressure": 1013,
            "humidity": 21,
            "dew_point": -3.65,
            "wind_speed": 9.32,
            "wind_deg": 324,
            "wind_gust": 14.07,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": 1,
            "pop": 0,
            "uvi": 3.38,
        },
        {
            "dt": 1704542400,
            "sunrise": 1704524331,
            "sunset": 1704561111,
            "moonrise": 1704505980,
            "moonset": 1704545520,
            "moon_phase": 0.82,
            "summary": "There will be clear sky until morning, then partly cloudy",
            "temp": {
                "day": 14.96,
                "min": 5.86,
                "max": 16.27,
                "night": 9.28,
                "eve": 12.84,
                "morn": 6.61,
            },
            "feels_like": {"day": 13.14, "night": 7.08, "eve": 10.96, "morn": 3.14},
            "pressure": 1020,
            "humidity": 24,
            "dew_point": -5.35,
            "wind_speed": 8.06,
            "wind_deg": 350,
            "wind_gust": 13.95,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": 59,
            "pop": 0,
            "uvi": 3.29,
        },
        {
            "dt": 1704628800,
            "sunrise": 1704610736,
            "sunset": 1704647557,
            "moonrise": 1704596100,
            "moonset": 1704634020,
            "moon_phase": 0.86,
            "summary": "You can expect partly cloudy in the morning, with clearing in the afternoon",
            "temp": {
                "day": 15.54,
                "min": 6.48,
                "max": 17.49,
                "night": 9.64,
                "eve": 12.57,
                "morn": 6.49,
            },
            "feels_like": {"day": 13.78, "night": 8.07, "eve": 10.59, "morn": 4.39},
            "pressure": 1020,
            "humidity": 24,
            "dew_point": -5.01,
            "wind_speed": 4.67,
            "wind_deg": 262,
            "wind_gust": 5.53,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": 76,
            "pop": 0,
            "uvi": 3.43,
        },
        {
            "dt": 1704715200,
            "sunrise": 1704697140,
            "sunset": 1704734005,
            "moonrise": 1704686340,
            "moonset": 1704723060,
            "moon_phase": 0.89,
            "summary": "You can expect clear sky in the morning, with partly cloudy in the afternoon",
            "temp": {
                "day": 16.06,
                "min": 6.44,
                "max": 17.88,
                "night": 11.01,
                "eve": 12.48,
                "morn": 6.5,
            },
            "feels_like": {"day": 14.14, "night": 8.79, "eve": 10.2, "morn": 4.51},
            "pressure": 1019,
            "humidity": 16,
            "dew_point": -9.88,
            "wind_speed": 3.1,
            "wind_deg": 300,
            "wind_gust": 3.18,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": 0,
            "pop": 0,
            "uvi": 3.78,
        },
        {
            "dt": 1704801600,
            "sunrise": 1704783542,
            "sunset": 1704820453,
            "moonrise": 1704776760,
            "moonset": 1704812580,
            "moon_phase": 0.92,
            "summary": "There will be partly cloudy today",
            "temp": {
                "day": 17.2,
                "min": 8.35,
                "max": 18.41,
                "night": 11.04,
                "eve": 13.21,
                "morn": 8.35,
            },
            "feels_like": {"day": 15.39, "night": 8.8, "eve": 11.08, "morn": 6.26},
            "pressure": 1017,
            "humidity": 16,
            "dew_point": -8.56,
            "wind_speed": 7,
            "wind_deg": 218,
            "wind_gust": 7.97,
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": 100,
            "pop": 0,
            "uvi": 3.33,
        },
        {
            "dt": 1704888000,
            "sunrise": 1704869943,
            "sunset": 1704906901,
            "moonrise": 1704867060,
            "moonset": 1704902700,
            "moon_phase": 0.96,
            "summary": "The day will start with partly cloudy through the late morning hours, transitioning to clearing",
            "temp": {
                "day": 17.93,
                "min": 8.19,
                "max": 19.79,
                "night": 11.15,
                "eve": 14.24,
                "morn": 8.19,
            },
            "feels_like": {"day": 16.2, "night": 9.1, "eve": 12.37, "morn": 5.81},
            "pressure": 1014,
            "humidity": 16,
            "dew_point": -7.89,
            "wind_speed": 6.55,
            "wind_deg": 223,
            "wind_gust": 8.16,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": 1,
            "pop": 0,
            "uvi": 4,
        },
        {
            "dt": 1704974400,
            "sunrise": 1704956342,
            "sunset": 1704993351,
            "moonrise": 1704957060,
            "moonset": 1704993300,
            "moon_phase": 0,
            "summary": "You can expect clear sky in the morning, with partly cloudy in the afternoon",
            "temp": {
                "day": 19.43,
                "min": 9.11,
                "max": 21.25,
                "night": 13.52,
                "eve": 15.57,
                "morn": 9.11,
            },
            "feels_like": {"day": 17.95, "night": 11.84, "eve": 14.02, "morn": 7.65},
            "pressure": 1016,
            "humidity": 20,
            "dew_point": -4.2,
            "wind_speed": 6.27,
            "wind_deg": 246,
            "wind_gust": 7.32,
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": 1,
            "pop": 0,
            "uvi": 4,
        },
        {
            "dt": 1705060800,
            "sunrise": 1705042739,
            "sunset": 1705079801,
            "moonrise": 1705046700,
            "moonset": 1705084080,
            "moon_phase": 0.04,
            "summary": "You can expect partly cloudy in the morning, with clearing in the afternoon",
            "temp": {
                "day": 15.02,
                "min": 8.17,
                "max": 16.52,
                "night": 9.89,
                "eve": 12.21,
                "morn": 8.17,
            },
            "feels_like": {"day": 13.52, "night": 7.97, "eve": 10.48, "morn": 5.1},
            "pressure": 1020,
            "humidity": 36,
            "dew_point": -0.01,
            "wind_speed": 7.69,
            "wind_deg": 49,
            "wind_gust": 10.53,
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": 62,
            "pop": 0,
            "uvi": 4,
        },
    ],
    "alerts": [
        {
            "sender_name": "Office National de la Météorologie",
            "event": "ORAGE",
            "start": 1704488400,
            "end": 1704488400,
            "description": "",
            "tags": ["Thunderstorm"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "PLUIE",
            "start": 1704488400,
            "end": 1704488400,
            "description": "",
            "tags": ["Rain"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "NEIGE ET VERGLAS",
            "start": 1704499200,
            "end": 1704499200,
            "description": "",
            "tags": ["Other dangers"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "NEIGE ET VERGLAS",
            "start": 1704499200,
            "end": 1704499200,
            "description": "",
            "tags": ["Other dangers"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "NEIGE ET VERGLAS",
            "start": 1704499200,
            "end": 1704499200,
            "description": "",
            "tags": ["Other dangers"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "ORAGE",
            "start": 1704488400,
            "end": 1704499200,
            "description": "",
            "tags": ["Thunderstorm"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "VENT VIOLENT",
            "start": 1704477600,
            "end": 1704510000,
            "description": "",
            "tags": ["Other dangers"],
        },
        {
            "sender_name": "Office National de la Météorologie",
            "event": "PLUIE",
            "start": 1704488400,
            "end": 1704499200,
            "description": "",
            "tags": ["Rain"],
        },
    ],
}

EXPECTED_OPENWEATHERMAP_FORECAST_GET_DATA_RESPONSE = [
    (
        "/sensor/insert-sensor-type",
        {
            "name": "Weather",
            "description": "Weather sensors and sensor-like data sources, such as weather forecast sources.",
            "measures": [
                {
                    "name": "temperature",
                    "units": "degrees Celsius",
                    "datatype": "float",
                },
                {
                    "name": "relative humidity",
                    "units": "percent",
                    "datatype": "integer",
                },
                {"name": "air pressure", "units": "millibar", "datatype": "integer"},
                {"name": "wind speed", "units": "m/s", "datatype": "float"},
                {"name": "wind direction", "units": "degrees", "datatype": "integer"},
                {"name": "rain", "units": "mms", "datatype": "float"},
                {"name": "icon", "units": "", "datatype": "string"},
            ],
        },
    ),
    (
        "/sensor/insert-sensor",
        {
            "unique_identifier": "OpenWeatherMapForecast",
            "type_name": "Weather",
            "name": "OpenWeatherMap Forecasts",
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "temperature",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": (16.69, 16.41),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "air pressure",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": (1011, 1011),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "relative humidity",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": (25, 26),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "wind speed",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": (5.25, 4.82),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "wind direction",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": (269, 264),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "icon",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": ("01d", "01n"),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
    (
        "/sensor/insert-sensor-readings",
        {
            "measure_name": "rain",
            "unique_identifier": "OpenWeatherMapForecast",
            "readings": (0.0, 0.0),
            "timestamps": ("2024-01-05T17:00:00", "2024-01-05T18:00:00"),
        },
    ),
]
