#!/bin/bash

# Test database
export DT_SQL_TESTUSER="<REPLACE_ME>"
export DT_SQL_TESTPASS="<REPLACE_ME>"
export DT_SQL_TESTHOST="<REPLACE_ME>"
export DT_SQL_TESTPORT="<REPLACE_ME>"
export DT_SQL_TESTDBNAME="<REPLACE_ME>"

# Docker
export DT_DOCKER_USER="<REPLACE_ME>"
export DT_DOCKER_PASS="<REPLACE_ME>"

# Openweather API
export DT_OPENWEATHERMAP_APIKEY="<REPLACE_ME>"

# Hyper AG API key
export DT_HYPER_APIKEY="<REPLACE_ME>"
