name: "Build and push backend to Docker image"

on:
  push:
    branches: [main, develop, test-actions]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: 'Build main'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker build -f Dockerfile_backend -t turingcropapp/nwtwin-backend:main .
          docker push turingcropapp/nwtwin-backend:main
      - name: 'Build dev'
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker build -f Dockerfile_backend -t turingcropapp/nwtwin-backend:dev .
          docker push turingcropapp/nwtwin-backend:dev
      - name: 'Build test-actions'
        if: ${{ github.ref == 'refs/heads/test-actions' }}
        run: |
          docker build -f Dockerfile_backend -t turingcropapp/nwtwin-backend:test-actions .
          docker push turingcropapp/nwtwin-backend:test-actions
