name: pre-commit
on: [push, pull_request]
env:
  PYTHON_VERSION: "3.10"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        npm install --prefix dtbase/frontend/ --include=dev
    - uses: pre-commit/action@v3.0.0
